name: Test cookiecutter

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} py3.12 dotNET 9.x
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          path: cookiecutter

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: true

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter

      - name: Set up dotNet 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: true

      - name: Test
        shell: pwsh
        run: |
          $JsonFile = (Get-Content -LiteralPath './.github/tests/replay.json' | ConvertFrom-Json -Depth 100 -AsHashtable);
          cookiecutter cookiecutter/ --replay-file './.github/tests/replay.json';

          If (-not (Test-Path -LiteralPath (Join-Path -Path $PWD -ChildPath "RimWorld-$($JsonFile.cookiecutter.mod_name -replace ' ','_')"))) {
            Throw "Failed to create cookiecutter template with name $($JsonFile.cookiecutter.mod_name)";
          }

          ForEach ($SupportedVersion in ($JsonFile.cookiecutter.supported_versions -split ',')) {
            dotnet build "./RimWorld-$($JsonFile.cookiecutter.mod_name -replace ' ','_')" -replace ' ','')" -c "$($SupportedVersion.Trim())";
          }
