name: Test cookiecutter

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} py3.12 dotNET 9.x
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Install python dependencies
        if: ${{ matrix.platform == 'windows-latest' }}
        shell: pwsh
        run: git config --system core.longpaths true

      - uses: actions/checkout@v4
        with:
          path: cookiecutter

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter jinja2_time

      - name: Set up dotNet 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Test
        shell: pwsh
        run: |
          $JsonFile = (Get-Content -LiteralPath './cookiecutter/.github/tests/replay.json' | ConvertFrom-Json -Depth 100 -AsHashtable);
          cookiecutter cookiecutter/ --replay-file './cookiecutter/.github/tests/replay.json';

          If (-not (Test-Path -LiteralPath (Join-Path -Path $PWD -ChildPath "RimWorld-$($JsonFile.cookiecutter.mod_name -replace ' ','_')"))) {
            Throw "Failed to create cookiecutter template with name $($JsonFile.cookiecutter.mod_name)";
          }

          $EXIT_CODE = 0;

          ForEach ($SupportedVersion in ($JsonFile.cookiecutter.supported_versions -split ',')) {
            Write-Host -Object "Building for $SupportedVersion";
            dotnet build "./RimWorld-$($JsonFile.cookiecutter.mod_name -replace ' ','_')" -c "$($SupportedVersion.Trim())";
            IF ($LASTEXITCODE -ne 0) {
              $EXIT_CODE = 1;
            }
          }

          Exit $EXIT_CODE;
